-- 1. Profiles (Trigger based) (from 20250110224500)
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  role text check (role in ('user', 'admin')) default 'user',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check ((select auth.uid()) = id);

create policy "Users can update own profile." on profiles
  for update using ((select auth.uid()) = id);

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, role)
  values (new.id, new.email, 'user');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to create profile on signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 2. Custom Types (from 20260120222500)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'content_status') THEN
        CREATE TYPE content_status AS ENUM ('draft', 'published', 'archived', 'deleted');
    END IF;
END $$;


-- 3. Sources (from 20260115160000 + 20260124000000 removal of status)
-- Note: status column added in 20260120 is REMOVED intentionally here
create table if not exists sources (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  slug text not null unique,
  icon_url text,
  url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table sources enable row level security;

-- Sources Policies (Consolidated from 20260115 and 20260124)
create policy "Sources are viewable by everyone" 
  on sources for select 
  using (true);

create policy "Sources are insertable by authenticated users" 
  on sources for insert 
  with check (auth.role() = 'authenticated');

create policy "Sources are updatable by authenticated users" 
  on sources for update 
  using (auth.role() = 'authenticated');

create policy "Sources are deletable by authenticated users" 
  on sources for delete 
  using (auth.role() = 'authenticated');


-- 4. Components (from 20250110224500 + updates)
create table components (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  code_string text, -- Made nullable in 20260111190500
  tags text[],
  original_app text,
  preview_url text, -- Added in 20260111185500
  thumbnail_url text, -- Added in 20260111200000
  source_id uuid references sources(id) on delete set null, -- Added in 20260115160000
  view_count bigint DEFAULT 0, -- Added in 20260119160000
  og_image_url text, -- Added in 20260119200000
  status content_status NOT NULL DEFAULT 'draft' -- Added in 20260120222500
);

COMMENT ON COLUMN components.og_image_url IS 'Static image URL for social sharing (OG/Twitter cards). Required when thumbnail_url is an MP4.';

-- View Count Function (from 20260119160000)
CREATE OR REPLACE FUNCTION increment_view_count(component_id_param bigint)
RETURNS void AS $$
BEGIN
  UPDATE components 
  SET view_count = view_count + 1 
  WHERE id = component_id_param;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

alter table components enable row level security;

-- Components Policies (Consolidated from 20250110, 20250111, 202601111948, 20260113, 20260120)
-- Public View: Only Published
CREATE POLICY "Components are viewable by public" ON components
    FOR SELECT USING (status = 'published');

-- Auth View: All (Admins/Creators)
CREATE POLICY "Components are viewable by authenticated users" ON components
    FOR SELECT USING (auth.role() = 'authenticated');

-- Auth Insert/Update/Delete (Relaxed from Admin only)
CREATE POLICY "Components are insertable by authenticated users" ON components
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Components are updatable by authenticated users" ON components
    FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Components are deletable by authenticated users" ON components
    FOR DELETE USING (auth.role() = 'authenticated');


-- 5. Component Variants (from 20260114133500)
create table if not exists public.component_variants (
  id uuid not null default gen_random_uuid(),
  component_id bigint not null references public.components(id) on delete cascade,
  name text not null,
  code_string text,
  preview_url text,
  is_default boolean default false,
  created_at timestamp with time zone not null default now(),
  constraint component_variants_pkey primary key (id)
);

alter table public.component_variants enable row level security;

create policy "Component variants are viewable by everyone"
  on public.component_variants for select
  using (true);

create policy "Component variants are insertable by authenticated users"
  on public.component_variants for insert
  with check (auth.role() = 'authenticated');

create policy "Component variants are updatable by authenticated users"
  on public.component_variants for update
  using (auth.role() = 'authenticated');

create policy "Component variants are deletable by authenticated users"
  on public.component_variants for delete
  using (auth.role() = 'authenticated');


-- 6. Flows (from 20250110224500 + updates)
create table flows (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  status content_status NOT NULL DEFAULT 'draft' -- Added in 20260120222500
);

alter table flows enable row level security;

-- Flows Policies (Consolidated)
CREATE POLICY "Flows are viewable by public" ON flows
    FOR SELECT USING (status = 'published');

CREATE POLICY "Flows are viewable by authenticated users" ON flows
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Flows are insertable by authenticated users" ON flows
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Note: Update policy for Flows wasn't explicitly seen in relax_rls but implied. Adding for consistency.
CREATE POLICY "Flows are updatable by authenticated users" ON flows
    FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Flows are deletable by authenticated users" ON flows
    FOR DELETE USING (auth.role() = 'authenticated');


-- 7. Flow Steps (from 20250110224500 + updates)
create table flow_steps (
  id bigint generated by default as identity primary key,
  flow_id bigint references flows(id) on delete cascade,
  component_id bigint references components(id) on delete cascade,
  step_order int not null,
  unique(flow_id, step_order)
);

alter table flow_steps enable row level security;

-- Flow Steps Policies (Consolidated)
CREATE POLICY "Flow Steps are viewable by everyone" ON flow_steps FOR SELECT USING (true);

CREATE POLICY "Flow Steps are insertable by authenticated users" ON flow_steps FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Note: Update policy wasn't explicitly seen. Adding.
CREATE POLICY "Flow Steps are updatable by authenticated users" ON flow_steps FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Flow Steps are deletable by authenticated users" ON flow_steps FOR DELETE USING (auth.role() = 'authenticated');


-- 8. Filters (from 20260111193500)
CREATE TABLE filter_definitions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  section text NOT NULL CHECK (section IN ('category', 'screen', 'ui_element', 'flow')),
  group_name text, -- e.g. "New User Experience", can be null for top-level like Categories
  name text NOT NULL, -- e.g. "Signup"
  slug text NOT NULL UNIQUE, -- e.g. "signup"
  definition text, -- description from Mobbin
  synonyms text[], -- synonyms for search
  created_at timestamptz DEFAULT now()
);

CREATE TABLE component_filters (
  component_id bigint REFERENCES components(id) ON DELETE CASCADE,
  filter_id uuid REFERENCES filter_definitions(id) ON DELETE CASCADE,
  PRIMARY KEY (component_id, filter_id)
);

CREATE INDEX idx_component_filters_filter_id ON component_filters(filter_id);
CREATE INDEX idx_component_filters_component_id ON component_filters(component_id);
CREATE INDEX idx_filter_definitions_section ON filter_definitions(section);
CREATE INDEX idx_filter_definitions_slug ON filter_definitions(slug);

ALTER TABLE filter_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE component_filters ENABLE ROW LEVEL SECURITY;

-- Filters Policies
CREATE POLICY "Public read filters" ON filter_definitions
  FOR SELECT USING (true);

CREATE POLICY "Public read component_filters" ON component_filters
  FOR SELECT USING (true);

CREATE POLICY "Authenticated insert filters" ON filter_definitions
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated update filters" ON filter_definitions
  FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated insert component_filters" ON component_filters
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated delete component_filters" ON component_filters
  FOR DELETE USING (auth.role() = 'authenticated');


-- 9. Storage (from 20260111185500)
INSERT INTO storage.buckets (id, name, public)
VALUES ('component-previews', 'component-previews', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public Read Access"
ON storage.objects FOR SELECT
USING ( bucket_id = 'component-previews' );

CREATE POLICY "Authenticated Upload Access"
ON storage.objects FOR INSERT
WITH CHECK (
  bucket_id = 'component-previews' 
  AND auth.role() = 'authenticated'
);

CREATE POLICY "Authenticated Update Access"
ON storage.objects FOR UPDATE
USING (
  bucket_id = 'component-previews' 
  AND auth.role() = 'authenticated'
);
